[build]
command = "npm run build"
publish = ".next"

# Pin Node for consistent builds
[build.environment]
NODE_VERSION = "20"

# Optional: monorepo
# base = "apps/web"

# Optional: function bundling tweaks for large deps
[functions]
node_bundler = "esbuild"
# external_node_modules = ["@prisma/client"]
